trigger:
- main

pool:
  name: 'Default'   

steps:
- script: |
    echo "¡Hola! Estoy corriendo en la computadora de Juan Gilberto."
    echo "Fecha y hora:"
    time /t
  displayName: 'Verificación de Agente Local'

- script: echo ¡El pipeline ha funcionado correctamente!
  displayName: 'Mensaje de Éxito'